version: '3'

services:
  laravel:
    image: kuwai/laravel:prod
    container_name: laravel
    networks:
      - laranet
  nginx:
    image: kuwai/nginx:prod
    container_name: nginx
    networks:
      - laranet
    ports:
      - "8080:80"

networks:
  bridge:
    - laranet